// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#ifndef ZCM_EMBEDDED
#include <stdio.h>
#endif
#include "test_msg.h"

static int __test_msg_hash_computed = 0;
static uint64_t __test_msg_hash;

uint64_t __test_msg_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __test_msg_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__test_msg_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xef3e5b5c283a2defLL
         + __string_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __test_msg_get_hash(void)
{
    if (!__test_msg_hash_computed) {
        __test_msg_hash = (int64_t)__test_msg_hash_recursive(NULL);
        __test_msg_hash_computed = 1;
    }

    return __test_msg_hash;
}

int __test_msg_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const test_msg* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].str), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int test_msg_encode(void* buf, uint32_t offset, uint32_t maxlen, const test_msg* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __test_msg_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __test_msg_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __test_msg_encoded_array_size(const test_msg* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __string_encoded_array_size(&(p[element].str), 1);

    }
    return size;
}

uint32_t test_msg_encoded_size(const test_msg* p)
{
    return 8 + __test_msg_encoded_array_size(p, 1);
}

int __test_msg_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, test_msg* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].str), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __test_msg_decode_array_cleanup(test_msg* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __string_decode_array_cleanup(&(p[element].str), 1);

    }
    return 0;
}

int test_msg_decode(const void* buf, uint32_t offset, uint32_t maxlen, test_msg* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __test_msg_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __test_msg_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int test_msg_decode_cleanup(test_msg* p)
{
    return __test_msg_decode_array_cleanup(p, 1);
}

uint32_t __test_msg_clone_array(const test_msg* p, test_msg* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __string_clone_array(&(p[element].str), &(q[element].str), 1);

    }
    return n;
}

test_msg* test_msg_copy(const test_msg* p)
{
    test_msg* q = (test_msg*) malloc(sizeof(test_msg));
    __test_msg_clone_array(p, q, 1);
    return q;
}

void test_msg_destroy(test_msg* p)
{
    __test_msg_decode_array_cleanup(p, 1);
    free(p);
}

int test_msg_publish(zcm_t* zcm, const char* channel, const test_msg* p)
{
      uint32_t max_data_size = test_msg_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = test_msg_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _test_msg_subscription_t {
    test_msg_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void test_msg_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    test_msg p;
    memset(&p, 0, sizeof(test_msg));
    status = test_msg_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr, "error %d decoding test_msg!!!\n", status);
        #endif
        return;
    }

    test_msg_subscription_t* h = (test_msg_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    test_msg_decode_cleanup (&p);
}

test_msg_subscription_t* test_msg_subscribe (zcm_t* zcm,
                    const char* channel,
                    test_msg_handler_t f, void* userdata)
{
    test_msg_subscription_t* n = (test_msg_subscription_t*)
                       malloc(sizeof(test_msg_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              test_msg_handler_stub, n);
    if (n->z_sub == NULL) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr,"couldn't reg test_msg ZCM handler!\n");
        #endif
        free (n);
        return NULL;
    }
    return n;
}

int test_msg_unsubscribe(zcm_t* zcm, test_msg_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        #ifndef ZCM_EMBEDDED
        fprintf(stderr,
           "couldn't unsubscribe test_msg_handler %p!\n", hid);
        #endif
        return -1;
    }
    free (hid);
    return 0;
}

