// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <zcm_coretypes.h>
#include <zcm.h>

#ifndef _channel_array_h
#define _channel_array_h

#ifdef __cplusplus
extern "C" {
#endif

#define CHANNEL_ARRAY_IS_LITTLE_ENDIAN 0
typedef struct _channel_array channel_array;
struct _channel_array
{
    int8_t     arduino_id;
    int8_t     sensor_id;
    int64_t    sz;
    double     *data;
    char*      units;
};

/**
 * Create a deep copy of a channel_array.
 * When no longer needed, destroy it with channel_array_destroy()
 */
channel_array* channel_array_copy(const channel_array* to_copy);

/**
 * Destroy an instance of channel_array created by channel_array_copy()
 */
void channel_array_destroy(channel_array* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _channel_array_subscription_t channel_array_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * channel_array is received.
 */
typedef void(*channel_array_handler_t)(const zcm_recv_buf_t* rbuf,
             const char* channel, const channel_array* msg, void* userdata);

/**
 * Publish a message of type channel_array using ZCM.
 *
 * @param zcm The ZCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means ZCM has transferred
 * responsibility of the message data to the OS.
 */
int channel_array_publish(zcm_t* zcm, const char* channel, const channel_array* msg);

/**
 * Subscribe to messages of type channel_array using ZCM.
 *
 * @param zcm The ZCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by ZCM when a message is received.
 *                This function is invoked by ZCM during calls to zcm_handle() and
 *                zcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return pointer to subscription type, NULL if failure. Must clean up
 *         dynamic memory by passing the pointer to channel_array_unsubscribe.
 */
channel_array_subscription_t* channel_array_subscribe(zcm_t* zcm, const char* channel, channel_array_handler_t handler, void* userdata);

/**
 * Removes and destroys a subscription created by channel_array_subscribe()
 */
int channel_array_unsubscribe(zcm_t* zcm, channel_array_subscription_t* hid);
/**
 * Encode a message of type channel_array into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to channel_array_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int channel_array_encode(void* buf, uint32_t offset, uint32_t maxlen, const channel_array* p);

/**
 * Decode a message of type channel_array from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with channel_array_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int channel_array_decode(const void* buf, uint32_t offset, uint32_t maxlen, channel_array* msg);

/**
 * Release resources allocated by channel_array_decode()
 * @return 0
 */
int channel_array_decode_cleanup(channel_array* p);

/**
 * Check how many bytes are required to encode a message of type channel_array
 */
uint32_t channel_array_encoded_size(const channel_array* p);

// ZCM support functions. Users should not call these
int64_t  __channel_array_get_hash(void);
uint64_t __channel_array_hash_recursive(const __zcm_hash_ptr* p);
int      __channel_array_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const channel_array* p, uint32_t elements);
int      __channel_array_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, channel_array* p, uint32_t elements);
int      __channel_array_decode_array_cleanup(channel_array* p, uint32_t elements);
uint32_t __channel_array_encoded_array_size(const channel_array* p, uint32_t elements);
uint32_t __channel_array_clone_array(const channel_array* p, channel_array* q, uint32_t elements);

#ifdef __cplusplus
}
#endif

#endif
